-- DML (Data Manipulation Laguage) -> 데이터 관점
-- DML : INSERT(입력), UPDATE(수정), DELETE(삭제)
-- DDL -> 테이블 관련 / DML -> 데이터 관련
-- 연습용 테이블 생성하기
CREATE TABLE DEPT_TEMP -- 복사 하면 제약 조건 빠지게 됨
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

DROP TABLE DEPT_TEMP;

-- 테이블에 데이터를 추가하는 INSERT 문
-- INSERT INTO 테이블명 (컬럼명...) VALUES (데이터...)
-- 프라이머리 키가 없다면 테이블의 기능을 못할 가능성이 있다.
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE', 'SEOUL')


INSERT INTO DEPT_TEMP VALUES (60, 'BACKEND', 'BUSAN');

INSERT INTO DEPT_TEMP(DEPTNO) VALUES (70);

INSERT INTO DEPT_TEMP VALUES (80, 'FRONTEND', 'INCHEON');

INSERT INTO DEPT_TEMP (DNAME, LOC) VALUES ('APP', 'DAEGU');

INSERT INTO DEPT VALUES (40, 'BACKEND', 'BUSAN');

SELECT * FROM DEPT_TEMP;

DELETE FROM DEPT_TEMP
WHERE DEPTNO = 70;

INSERT INTO DEPT_TEMP VALUES (70, '웹개발','');

CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP
WHERE 1 != 1;

DROP TABLE EMP_TEMP;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
	VALUES (9001, '나영석', 'PD', NULL, '2020/01/01', 9900, 1000, 50);
	
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
	VALUES (9002, '강호동', 'MC', NULL, TO_DATE('2021/01/02', 'YYYY/MM/DD'), 8000, 1000, 60);
	
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
	VALUES (9003, '서장훈', 'MC', NULL, SYSDATE, 9000, 1000, 70);
	
ROLLBACK;

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES(80, 'FRONTEND', 'SUWON');
ROLLBACK;

UPDATE DEPT_TEMP -- AUTO COMMIT / COMMIT이 끝나야만 다른 곳에서 작업 가능
	SET DNAME = 'WEB-PROGRAM',
		LOC = 'SUWON'
	WHERE DEPTNO = 70; 
	
COMMIT;

ROLLBACK;

DELETE FROM DEPT_TEMP
	WHERE LOC = 'SUWON';